#!/usr/bin/env python3 
# Quest 2: The naming Ceremony

hero_name = "Aeloria"
superpower = "Chronomancy (Time Manipulation)

print("Introduction the legendary hero, " + hero_name + "! Armed with the exraordinary power of " + superpower + " .")
